version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: emission-analyzer-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_NAME}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  web:
    build: .
    container_name: emission-analyzer-api
    restart: always
    volumes:
      - .:/app
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      - db
    environment:
      DJANGO_SETTINGS_MODULE: "api.settings.prod"
      START_CMD: "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn api.wsgi:application --bind 0.0.0.0:${API_PORT}"
    env_file:
      - .env
  
  model:
    build:
      context: ${PATH_TO_MODEL}
    container_name: emission-analyzer-model
    restart: always
    ports:
      - "${MODEL_PORT}:${MODEL_PORT}"
    networks:
      - emission-analyzer-service_default
    command: sh ./server.sh

volumes:
  postgres_data:

networks:
  emission-analyzer-service_default:
    external: true