HTTP_METHOD_POST = "POST"
HTTP_METHOD_GET = "GET"
HTTP_METHOD_PUT = "PUT"
HTTP_METHOD_DELETE = "DELETE"

USER_ID = "user_id"
ENGINE = "engine"
ENGINE_ID = "engine_identification"
ENGINE_TYPE = "engine_type"
BP_RATIO = "bp_ratio"
PRESSURE_RATIO = "pressure_ratio"
RATED_THRUST = "rated_thrust"
