# Generated by Django 5.1.6 on 2025-03-24 00:52

from django.db import migrations

def add_engine_types(apps, schema_editor):
    EngineType = apps.get_model("emission_analyzer_api", "EngineType")
    EngineType.objects.bulk_create([
        EngineType(type="turbofan"),
        EngineType(type="mixed turbofan"),
    ], ignore_conflicts=True)  # Prevents duplicates

class Migration(migrations.Migration):

    dependencies = [
        ('emission_analyzer_api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_engine_types),  # Add the function to create engine types
    ]
