# Generated by Django 5.1.7 on 2025-04-06 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emission_analyzer_api', '0002_add_engine_types'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='engine',
            constraint=models.UniqueConstraint(fields=('user', 'engine_identification'), name='unique_user_engine_identification'),
        ),
    ]
