# Generated by Django 5.1.6 on 2025-04-06 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emission_analyzer_api', '0003_engine_unique_user_engine_identification'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE emission_analyzer_api_engine DROP CONSTRAINT IF EXISTS emission_analyzer_api_en_engine_identification_a0b28b0e_uniq;",
            reverse_sql="ALTER TABLE emission_analyzer_api_engine ADD CONSTRAINT emission_analyzer_api_en_engine_identification_a0b28b0e_uniq UNIQUE (engine_identification);"
        ),
    ]
