# Generated by Django 5.1.7 on 2025-04-08 01:25

from django.db import migrations

def add_emission_types(apps, schema_editor):
    EmissionType = apps.get_model("emission_analyzer_api", "EmissionType")
    EmissionType.objects.bulk_create([
        EmissionType(name="CO"),
        EmissionType(name="NOx"),
    ], ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('emission_analyzer_api', '0005_emissionclass_emissiontype_prediction'),
    ]

    operations = [
        migrations.RunPython(add_emission_types),
    ]
