# Generated by Django 5.1.7 on 2025-04-08 02:26

from django.db import migrations

def add_emission_classes(apps, schema_editor):
    EmissionClass = apps.get_model("emission_analyzer_api", "EmissionClass")
    EmissionClass.objects.bulk_create([
        EmissionClass(label="Low"),
        EmissionClass(label="Moderate"),
        EmissionClass(label="High"),
        EmissionClass(label="Very High"),
    ], ignore_conflicts=True)

class Migration(migrations.Migration):

    dependencies = [
        ('emission_analyzer_api', '0006_auto_20250408_0125'),
    ]

    operations = [
        migrations.RunPython(add_emission_classes),
    ]
