# Generated by Django 5.2 on 2025-05-01 01:33

from django.db import migrations

def capitalize_engine_types(apps, schema_editor):
    EngineType = apps.get_model("emission_analyzer_api", "EngineType")

    updates = {
        "turbofan": "Turbofan",
        "mixed turbofan": "Mixed Turbofan"
    }

    for old_type, new_type in updates.items():
        EngineType.objects.filter(type=old_type).update(type=new_type)


class Migration(migrations.Migration):

    dependencies = [
        ('emission_analyzer_api', '0007_auto_20250408_0226'),
    ]

    operations = [
        migrations.RunPython(capitalize_engine_types),
    ]
